services:
  # Backend API service
  - type: web
    name: speedtest-backend
    env: node
    buildCommand: npm run build:backend
    startCommand: cd backend && npm start
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

  # Frontend service
  - type: web
    name: speedtest-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./project/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production